### ISSUE TITLE
How to make Radial Circle Silder start from top 

### ISSUE THREAD

**Issue by gaus694** [SimformSolutionsPvtLtd/react-native-radial-slider#32]

**Comment by jeremypagley** [comment]
@gaus694 Any answers on this?

**Comment by mukesh-simform** [comment]
@jeremypagley Could you please add more information or share any screenshots, of what exactly you want to achieve so that we'll check that feasibility with the currently available version and get back?

**Comment by keremlx** [comment]
This would be useful when you're dealing with directional data and the default is North at 0 degrees, for example:
<img width="272" alt="Screenshot 2023-02-07 at 9 33 11 am" src="https://user-images.githubusercontent.com/123337648/217102632-13201b88-46f3-4bb9-a7fb-5c7a990f39ee.png">

**Comment by phamhoaivu911** [comment]
@mukesh-simform May I ask if there are any updates on this issue?

**Comment by mukesh-simform** [comment]
@phamhoaivu911, Thank you for your interest in this issue. We understand its importance and are actively working on resolving it. Stay tuned for the upcoming release, where we aim to address this issue.

**Comment by mahmoudrensol** [comment]
if i use three slider in one page the slider will be very slow 
performance will decrease

**Comment by MussadiqAli** [comment]
@gaus694 to start form top pass the prop "startAngle={90}"
