### ISSUE TITLE
Unable to change slider value manually from input box

### ISSUE THREAD

**Issue by AzherMansoori** [SimformSolutionsPvtLtd/react-native-radial-slider#35]
@mukesh-simform @parth-simform  
I want to change slider thumb position(value) on TextInput onTextChange but unable to do this.

 const [avalue, setValue] = useState(0);
 <View style={styles.container}>

      <RadialSlider
        value={avalue} // passing the updated state value is not working.
        min={0}
        max={200}
        onChange={(v)=>console.log(">>>",v)} // onChange not even calling when updating value from text input.
      />
      <TextInput
        style={{
          width: 200,
          height: 50,
          borderColor: 'blue',
          borderRadius: 4,
          borderWidth: 1,
          marginBottom:10
        }}
        value={String(avalue)}
        placeholder="Amount"
        onChangeText={(v)=> setValue(Number(v))}></TextInput>

    </View>

<img width="352" alt="Untitled 4" src="https://user-images.githubusercontent.com/26295783/225843667-6854bf13-33c3-4fb4-9a4b-3e6545a18ea9.png">

**Comment by mukesh-simform** [comment]
@AzherMansoori Thank you for bringing this to our attention. We'll make sure to address this issue as soon as possible.
Alternatively, If you'd like to contribute to fixing this issue, feel free to submit a pull request.

**Comment by AzherMansoori** [comment]
@mukesh-simform fixed this issue but seems i cannot push my changes to this repo. 
<img width="634" alt="Untitled" src="https://user-images.githubusercontent.com/26295783/226274197-880f1d55-03f9-4b0e-8389-6d14ee6d6aa8.png">

**Comment by wygarner** [comment]
@AzherMansoori How were you able to fix this issue? I am facing a similar problem

**Comment by hoonguyen** [comment]
@mukesh-simform This tool is very useful. I'd really appreciate it if you could update to a new version that fixed this render bug.

**Comment by AzherMansoori** [comment]
> @AzherMansoori How were you able to fix this issue? I am facing a similar problem

Hi @wygarner 
Go to >  node_modules/react-native-radial-slider/lib/components/RadialSlider/hooks/useSilderAnimation.js
Add following code snippet inside useSliderAnimation.js file.
 useEffect(()=>{
        setValue(props.value);
        onChange(props.value);
    },[props.value])
    
<img width="841" alt="radial_slider_issue" src="https://user-images.githubusercontent.com/26295783/233022520-be0f4e56-b08d-491e-a4ff-c858a45b38fe.png">

that's it. Enjoy Coding
