### ISSUE TITLE
RadialSlider there is a problem with

### ISSUE THREAD

**Issue by hanjin0523** [SimformSolutionsPvtLtd/react-native-radial-slider#36]
The library is working very well. thank you . But I have a problem. I will explain it while looking at the code below.

`const Dial = () => {

  const [temp, setTemp] = useState(0);
  const hum = 10;
  const time = "08:10";
  console.log(temp,"temp")
  const increase = () => {
    setTemp(temp + 5);
  };

  const decrease = () => {
    setTemp(temp => temp - 5); // speed 상태값을 5 감소시킵니다.
  };

  return(
    <>
      <View style={styles.tempHumTimeBox}>
        <Image 
              source={require("./assets/image/settingView/tempView.png")} 
              resizeMode="contain"
              style={styles.tempIcon}/>
        <Text style={styles.tempText}>{temp}<Text style={{fontSize:18}}>°C</Text></Text>
        <Image 
              source={require("./assets/image/settingView/humView.png")} 
              resizeMode="contain"
              style={styles.tempIcon}/>
        <Text style={styles.tempText}>{hum}<Text style={{fontSize:18}}>%</Text></Text>
        <Image 
              source={require("./assets/image/settingView/timeView.png")} 
              resizeMode="contain"
              style={styles.tempIcon}/>
        <Text style={styles.tempText}>{time}</Text>
      </View>
    <View style={styles.container}>
      <TouchableOpacity 
        onPress={decrease}
      >
        <Image 
          source={require('./assets/image/settingView/minusButton.png')} 
          resizeMode="center"
          style={styles.decreaseButton}/>
      </TouchableOpacity>
      <View style={{width:100,height:30,position:"absolute",marginTop:-70}}>
        <Text style={{marginLeft:30,fontSize:20, color:"black",fontWeight:"500"}}>40<Text style={{fontSize:14}}>°C</Text></Text>
      </View>
      <View style={{width:470,height:30,position:"absolute",marginTop:90,marginRight:0}}>
        <Text style={{fontSize:20, color:"black",fontWeight:"500", marginLeft:50}}>20<Text style={{fontSize:14}}>°C</Text></Text>
      </View>
      <View style={{width:500,height:30,position:"absolute",marginTop:90}}>
        <Text style={{fontSize:20, color:"black",fontWeight:"500",marginLeft:400}}>80<Text style={{fontSize:14}}>°C</Text></Text>
      </View>
      <RadialSlider props={temp}
        style={styles.mainCircle}
        step={3}
        variant={'radial-circle-slider'}
        value={temp}
        valueStyle={{fontSize:60,color:"black",alignItems:"center",justifyContent:"center", marginTop:20}}
        min={10}
        max={80}
        onChange={setTemp}
        radius={123}
        isHideSubtitle={Boolean}
        isHideTitle={Boolean} 
        unit={'°C'}
        unitStyle={{marginLeft:0,fontWeight:"bold",marginTop:35}}
        thumbColor={'#FF7345'}
        thumbRadius={11}
        thumbBorderWidth={5}
        sliderWidth={7}
        linearGradient ={[ { offset: '0%', color:'#FFD76F' }, 
                        { offset: '100%', color: '#FF7345' }]}
      />
      <View style={styles.circle}></View>
      <TouchableOpacity
        onPress={increase}
      >
        <Image 
          source={require('./assets/image/settingView/plusButton.png')} 
          resizeMode="center"
          style={styles.increaseButton}/>
      </TouchableOpacity>
    </View>
    </>
  );
};`

I want to make it possible to change the value (temp) of RadialSlider with the function increase discrease. However, when I take a log, there is a phenomenon that temp has changed but re-rendering does not work. Is there a way to solve this? No matter how I look at it, I don't know how to do it, so please help me!

**Comment by wygarner** [comment]
@hanjin0523 

I'm having a similar issue. I have a horizontal flat list with each item in the last spanning the size of the screen. One item in my list has the radial slider. I would like to reset to 0 after moving to the next item in the list but I can't get the slider to re-render after programmatically changing the value.

Were you able to find a solution to your problem?
