### ISSUE TITLE
Track Becomes Distorted when Slider Nears End

### ISSUE THREAD

**Issue by dylanreich** [SimformSolutionsPvtLtd/react-native-radial-slider#44]
![slider](https://github.com/SimformSolutionsPvtLtd/react-native-radial-slider/assets/271831/eb2c6e93-f573-4894-9183-d37a9c55929c)

For some reason when the slider reaches the end, the track starts to become distorted. I did some digging into the subviews and it seems to be related to the AnimatedPath object, along with its `animatedProps`.

**Comment by mukesh-simform** [comment]
@dylanreich Thank you for reporting this issue. We'll investigate and make necessary updates.

**Comment by MussadiqAli** [comment]
pass key prop to the slider with min value. its solve my problem.
<RadialSlider
key={your min value for slider}
>
