### ISSUE TITLE
How can reduce space between min and mix?

### ISSUE THREAD

**Issue by Yagnesh7028** [SimformSolutionsPvtLtd/react-native-radial-slider#46]
Hello,
I want to reduce a space between this two points, how can i do it?
![Screenshot 2023-12-21 at 6 04 29 PM](https://github.com/SimformSolutionsPvtLtd/react-native-radial-slider/assets/17902020/cd920302-c763-49d7-aac3-d443cf5356b4)

**Comment by mukesh-simform** [comment]
You'll need to reduce the size of the slider to achieve this. Unfortunately, there isn't a direct prop available to manage the space between the points. However, you can contribute by raising a pull request. Thank you.
