### ISSUE TITLE
[Request] Slider track color to have linearGradient option

### ISSUE THREAD

**Issue by hristo87** [SimformSolutionsPvtLtd/react-native-radial-slider#53]
Could you please add option for slider track color to use Linear Gradient as well.  It will be useful for controlling a temperature, for instance blue from one side going to red from the other. Thank you in advance!

**Comment by 6ase** [comment]
Its already done:
```
 linearGradient={
          [ { offset: '0%', color: THEME_CONSTANTS.COLORS[theme].CIRCLE_SLIDER.START },
           { offset: '50%', color: THEME_CONSTANTS.COLORS[theme].CIRCLE_SLIDER.END }]}
```

**Comment by hristo87** [comment]
thanks!
