### ISSUE TITLE
[REQUEST] Range slider

### ISSUE THREAD

**Issue by kecoco16** [SimformSolutionsPvtLtd/react-native-radial-slider#55]
Hello guys, first of all, thank you very much for all the effort creating this library.

Currently there is no variant of the slider to use as a range field which is very useful for many scenarios, so I would like to know if you have in mind at some point adding this functionality or if it could be a good contribution for a PR?

e.g.

<img width="271" alt="range2" src="https://github.com/SimformSolutionsPvtLtd/react-native-radial-slider/assets/25941813/4a0dbb1a-4678-4424-b7ab-368402d25baa">
<img width="377" alt="range" src="https://github.com/SimformSolutionsPvtLtd/react-native-radial-slider/assets/25941813/9e4b862e-baa2-4e5e-bebc-b06d9fd7400d">

**Comment by mukesh-simform** [comment]
@kecoco16 We're committed to resolving the major issues and enhancing existing variants and that's our top priority as of now,  However, If you would like to contribute, Feel free to create a pull request! Thank you!
